baseURL = 'https://blog.wjjblog.ccwu.cc/'
languageCode = 'zh-CN'
title = 'WJJ Blog'
theme = 'PaperMod'

[params]
  author = 'WJJ'
  description = 'Data Science & Development'
  defaultTheme = 'dark'
  mainSections = ["posts"]
  ShowReadingTime = true
  ShowShareButtons = false
  ShowPostNavLinks = true
  ShowBreadCrumbs = true
  ShowCodeCopyButtons = true

  [params.assets]
    favicon = "/favicon.svg"

  [params.giscus]
    repo = "wnzmb/wjj-blog"
    repoID = "R_kgDOTHEU5w"
    category = "Announcements"
    categoryID = "DIC_kwDOTHEU584DAFCT"
    mapping = "pathname"
    reactionsEnabled = "1"
    emitMetadata = "0"
    inputPosition = "bottom"
    theme = "dark"
    lang = "zh-CN"

  [params.editPost]
    URL = "https://github.com/wnzmb/wjj-blog/edit/main/"
    Text = "在 GitHub 上编辑此页"
    appendFilePath = true

  [[params.socialIcons]]
    name = 'github'
    url = 'https://github.com/wnzmb'

[menu]
  [[menu.main]]
    identifier = 'posts'
    name = '文章'
    url = '/posts/'
    weight = 10
  [[menu.main]]
    identifier = 'tags'
    name = '标签'
    url = '/tags/'
    weight = 20
  [[menu.main]]
    identifier = 'archives'
    name = '归档'
    url = '/archives/'
    weight = 30
  [[menu.main]]
    identifier = 'resume'
    name = '简历'
    url = '/resume/'
    weight = 40

[outputs]
  home = ['HTML', 'RSS', 'JSON']

[sitemap]
  changefreq = 'weekly'
  filename = 'sitemap.xml'
  priority = 0.5
