baseURL = 'https://blog.wjjblog.ccwu.cc/'
languageCode = 'zh-CN'
title = 'WJJ Blog'
theme = 'PaperMod'

[params]
  author = 'WJJ'
  description = 'Data Science & Development'
  defaultTheme = 'dark'
  mainSections = ["posts"]
  ShowReadingTime = true
  ShowShareButtons = false
  ShowPostNavLinks = true
  ShowBreadCrumbs = true
  ShowCodeCopyButtons = true

  [[params.socialIcons]]
    name = 'github'
    url = 'https://github.com/wnzmb'

[menu]
  [[menu.main]]
    identifier = 'posts'
    name = '文章'
    url = '/posts/'
    weight = 10
  [[menu.main]]
    identifier = 'tags'
    name = '标签'
    url = '/tags/'
    weight = 20
  [[menu.main]]
    identifier = 'archives'
    name = '归档'
    url = '/archives/'
    weight = 30
  [[menu.main]]
    identifier = 'resume'
    name = '简历'
    url = '/resume/'
    weight = 40

[outputs]
  home = ['HTML', 'RSS', 'JSON']
